### ISSUE TITLE
Be able to run code before server start

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/rapptor#31]
Would be nice to be able to hook in and run some code before the actual server is started.

Trying to implement some authentication but server.auth.strategy needs to be called before the routes are loaded.

Any ideas on the best way to do this?

---

This works but it feels dirty:

```
rapptor.server.register(require('hapi-auth-basic'), function (err) {
  rapptor.server.auth.strategy('simple', 'basic', { validateFunc: validate });
  rapptor.start();
});
```

**Comment by jgallen23** [comment]
Set up that code before calling rapptor.start. Will that work?

**Comment by dawnerd** [comment]
That would work only if Im not relying on the plugin loader to do its thing.

**Comment by jgallen23** [comment]
Ahh. Yeah. I see what you mean. Hmm...

**Comment by jgallen23** [comment]
I wonder if we could do some sort of middleware thing where you can hook into different states of the loading process. Might be overkill though

**Comment by jgallen23** [comment]
Or in the plugin loader, we pass in a file that gets run after that plugin is loaded

**Comment by dawnerd** [comment]
Looking at the hapi docs, this might be what we can use: http://hapijs.com/api#serveraftermethod-dependencies. Could probably just expose it has a helper.

**Comment by jgallen23** [comment]
added authPlugins and strategies to make this work
