### ISSUE TITLE
Built in log and stringify helpers

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/rapptor#44]
We use these quite frequently.

```js
module.exports = function (input) {
  console.log(input);
};
```

and

```js
var Handlebars = require('handlebars');
module.exports = function(input, pretty) {
  var spaces = (pretty) ? '  ' : '';
  return new Handlebars.SafeString(JSON.stringify(input, null, spaces));
};
```

Might be worth moving them into rapptor core?

**Comment by jgallen23** [comment]
Yeah. Good idea. Should we just put them in rapptor core or should we create a handlebars helper repo?

**Comment by dawnerd** [comment]
A different repo could be cool too, maybe something like rapptor-helpers? We bind server to the helpers so that might throw a wrench in making them completely unusable on other non rapptor projects

**Comment by jgallen23** [comment]
Oh. Good point. Let's just add to rapptor for now. Grab the common ones from our other projects too
