### ISSUE TITLE
config issues

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/rapptor#50]
so we refactored to use the {{name}}, but internally, we run confi twice, one for the default config and one for the app's config, so {{name}} is already processed before we get to the app's config.  Should we add support in confi to allow multiple directories or is there another way to handle this?

**Comment by dawnerd** [comment]
Yeah, I think multiple directories is the way to go. Could have `path` take an array of paths or a single string.

**Comment by jgallen23** [comment]
That sounds perfect
