### ISSUE TITLE
Built in error handling breaks json output

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/rapptor#58]
If a route returns a non html response it's broken. Need to check the response type before loading the error view.

**Comment by dawnerd** [comment]
Maybe an option for exclude paths, checking the response type wouldn't really work.

**Comment by jgallen23** [comment]
Why can't we check the content type header?

**Comment by dawnerd** [comment]
Pretty sure Boom errors will cause hapi to always think its json. Then theres the issue with 404s. It wont know if it needs to show the html 404 page on api calls.
