### ISSUE TITLE
Support s3 urls in asset helper

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/rapptor#61]
If I were to pass a full s3 url to the asset helper it would try to prepend the cdn path to it. Would be nice if we could either detect if its a full url and just spit it out as-is or transform the url into a cdn version. Might need an option for an image cdn host though.

**Comment by jgallen23** [comment]
whats the use case to pass in a full url to the asset helper?

**Comment by dawnerd** [comment]
Biggest case would be outputting an image from the db and not knowing if its a full url or a path to a local resource. I think the real value would be in creating a cdn version.

**Comment by jgallen23** [comment]
makes sense
