### ISSUE TITLE
Plugin options in config

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/rapptor#64]
Currently we only pass plugin options that go straight to the plugin. hapi has another set of options that are very useful and would be nice if we could configure them from the configs as well.

http://hapijs.com/api#serverregisterplugins-options-callback (Options right after plugins). This would allow us to remove the hardcoded options for prefixes from our plugins and provide better vhost support.

**Comment by jgallen23** [comment]
Interesting. Haven't used that before. What's the use case?

**Comment by dawnerd** [comment]
Biggest one is prefix on routes created by plugins.

**Comment by jgallen23** [comment]
so would that be a object that gets passed for all plugins?  or would you want to be able to set it for a specific plugin?

**Comment by dawnerd** [comment]
It would be for each plugin, but Im sure we can have some global option as well.

**Comment by jgallen23** [comment]
makes sense.  We'd have to change how we load plugins now, but seems like something we should support
