### ISSUE TITLE
run method from command line

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/rapptor#71]
There have been instances where I'd love to run a server method from the command line.  Here's what I'm thinking:

* rapptor checks if the first argument passed is `method`
* if it is, don't start the server, but still process everything (basically run `setup`)
* the next argument after `method` is the name of the method
* be able to support `namespaced.methods`
* be able to take in arguments like: `node server.js method jobs.fetchData test 123`
* be able to take in json arguments:  `node server.js method jobs.fetchData "{ test: 123 }"`
* the output of the method is displayed in the console via `JSON.stringify` to make it look nice

has anybody else needed something like this?

**Comment by ecwillis** [comment]
Yeah. That'd be great, esp. with the hapi-jobs lib, testing the methods there.
